name = "afrcloud-siren"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true


#routes = []

[[kv_namespaces]]
binding = "SIREN"
id = ""

[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "bbbbbbbb-cccc-4ddd-eeee-ffffffffffff"
#MAIN_PAGE_URL = "https://raw.githubusercontent.com/AFRcloud/AFR-Cloud/refs/heads/master/web/index.html"
#SUB_PAGE_URL = "https://raw.githubusercontent.com/AFRcloud/AFR-Cloud/refs/heads/master/web/sub.html"
#LINK_PAGE_URL = "https://raw.githubusercontent.com/AFRcloud/AFR-Cloud/refs/heads/master/web/link.html"
#CONVERTER_PAGE_URL = "https://raw.githubusercontent.com/AFRcloud/AFR-Cloud/refs/heads/master/web/converter.html"
